namespace: forgejo

persistence:
  storageClass: ""
  size: 10Gi

forgejo:
  image: codeberg.org/forgejo/forgejo:9
  replicas: 1
  rootUrl: ""
  service:
    type: ClusterIP
    port: 3000

runner:
  replicas: 2
  authKey: ""
  forgejoInstanceUrl: ""
  token: ""
  service:
    port: 8080
