apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: {{ .Values.namespace }}
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: forgejo
  ports:
    - port: {{ .Values.forgejo.service.port }}
      targetPort: {{ .Values.forgejo.service.port }}
